# Wraith Hardware Configuration
#
# Generated by nixos-generate-config.
# Contains hardware-specific settings derived from the physical machine.
{ config, lib, pkgs, modulesPath, ... }:

{
  imports = [
    (modulesPath + "/installer/scan/not-detected.nix")
  ];

  # Boot modules
  boot.initrd.availableKernelModules = [ "xhci_pci" "nvme" "uas" "sd_mod" "rtsx_pci_sdmmc" ];
  boot.initrd.kernelModules = [];
  boot.kernelModules = [ "kvm-intel" ];
  boot.extraModulePackages = [];

  # Filesystems (P15 ThinkPad dual NVMe layout)
  fileSystems."/" = {
    device = "/dev/disk/by-uuid/d31de144-5886-4bbe-8ab9-994e7c0558cb";
    fsType = "ext4";
  };

  fileSystems."/boot" = {
    device = "/dev/disk/by-uuid/4AC0-4760";
    fsType = "vfat";
    options = [ "fmask=0077" "dmask=0077" ];
  };

  fileSystems."/home" = {
    device = "/dev/disk/by-uuid/399eb6db-df7f-407b-8c98-6ef0956a05b7";
    fsType = "ext4";
  };

  swapDevices = [];

  # Platform
  nixpkgs.hostPlatform = lib.mkDefault "x86_64-linux";
  hardware.cpu.intel.updateMicrocode = lib.mkDefault config.hardware.enableRedistributableFirmware;
}
